# Generated by Django 5.0.3 on 2024-04-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_customuser_api_key_apikey_paymentinformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription_package',
            field=models.CharField(default='basic', max_length=100),
        ),
    ]
